native2ascii -encoding utf8 src\cuploader\text_utf8\messages.properties src\cuploader\text\messages.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_ar.properties src\cuploader\text\messages_ar.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_ast.properties src\cuploader\text\messages_ast.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_bn.properties src\cuploader\text\messages_bn.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_br.properties src\cuploader\text\messages_br.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_ca.properties src\cuploader\text\messages_ca.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_cs_CZ.properties src\cuploader\text\messages_cs_CZ.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_da.properties src\cuploader\text\messages_da.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_de.properties src\cuploader\text\messages_de.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_eo.properties src\cuploader\text\messages_eo.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_es_ES.properties src\cuploader\text\messages_es_ES.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_eu.properties src\cuploader\text\messages_eu.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_fa.properties src\cuploader\text\messages_fa.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_fi.properties src\cuploader\text\messages_fi.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_fo.properties src\cuploader\text\messages_fo.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_fr.properties src\cuploader\text\messages_fr.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_gl.properties src\cuploader\text\messages_gl.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_gu.properties src\cuploader\text\messages_gu.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_he.properties src\cuploader\text\messages_he.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_it_IT.properties src\cuploader\text\messages_it_IT.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_ja.properties src\cuploader\text\messages_ja.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_ka.properties src\cuploader\text\messages_ka.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_kk-cyrl.properties src\cuploader\text\messages_kk-cyrl.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_km.properties src\cuploader\text\messages_km.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_ko.properties src\cuploader\text\messages_ko.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_ksh.properties src\cuploader\text\messages_ksh.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_ku-latn.properties src\cuploader\text\messages_ku-latn.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_lb.properties src\cuploader\text\messages_lb.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_lt.properties src\cuploader\text\messages_lt.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_mk.properties src\cuploader\text\messages_mk.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_ml.properties src\cuploader\text\messages_ml.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_mn.properties src\cuploader\text\messages_mn.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_mr.properties src\cuploader\text\messages_mr.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_ms.properties src\cuploader\text\messages_ms.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_nl.properties src\cuploader\text\messages_nl.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_oc.properties src\cuploader\text\messages_oc.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_pa.properties src\cuploader\text\messages_pa.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_pl_PL.properties src\cuploader\text\messages_pl_PL.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_ps.properties src\cuploader\text\messages_ps.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_pt_BR.properties src\cuploader\text\messages_pt_BR.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_pt_PT.properties src\cuploader\text\messages_pt_PT.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_ru.properties src\cuploader\text\messages_ru.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_sa.properties src\cuploader\text\messages_sa.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_sr-ec.properties src\cuploader\text\messages_sr-ec.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_sv_SE.properties src\cuploader\text\messages_sv_SE.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_sw.properties src\cuploader\text\messages_sw.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_tr.properties src\cuploader\text\messages_tr.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_tt-cyrl.properties src\cuploader\text\messages_tt-cyrl.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_uk.properties src\cuploader\text\messages_uk.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_ur.properties src\cuploader\text\messages_ur.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_xmf.properties src\cuploader\text\messages_xmf.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_zh-hant.properties src\cuploader\text\messages_zh-hant.properties
native2ascii -encoding utf8 src\cuploader\text_utf8\messages_zh_CN.properties src\cuploader\text\messages_zh_CN.properties