D:
cd D:\Projekty\vicuna\src\cuploader
native2ascii -encoding utf8 text_utf8\messages.properties text\messages.properties
native2ascii -encoding utf8 text_utf8\messages_ar.properties text\messages_ar.properties
native2ascii -encoding utf8 text_utf8\messages_ast.properties text\messages_ast.properties
native2ascii -encoding utf8 text_utf8\messages_bn.properties text\messages_bn.properties
native2ascii -encoding utf8 text_utf8\messages_br.properties text\messages_br.properties
native2ascii -encoding utf8 text_utf8\messages_ca.properties text\messages_ca.properties
native2ascii -encoding utf8 text_utf8\messages_cs_CZ.properties text\messages_cs_CZ.properties
native2ascii -encoding utf8 text_utf8\messages_da.properties text\messages_da.properties
native2ascii -encoding utf8 text_utf8\messages_de.properties text\messages_de.properties
native2ascii -encoding utf8 text_utf8\messages_eo.properties text\messages_eo.properties
native2ascii -encoding utf8 text_utf8\messages_es_ES.properties text\messages_es_ES.properties
native2ascii -encoding utf8 text_utf8\messages_eu.properties text\messages_eu.properties
native2ascii -encoding utf8 text_utf8\messages_fa.properties text\messages_fa.properties
native2ascii -encoding utf8 text_utf8\messages_fi.properties text\messages_fi.properties
native2ascii -encoding utf8 text_utf8\messages_fo.properties text\messages_fo.properties
native2ascii -encoding utf8 text_utf8\messages_fr.properties text\messages_fr.properties
native2ascii -encoding utf8 text_utf8\messages_gl.properties text\messages_gl.properties
native2ascii -encoding utf8 text_utf8\messages_he.properties text\messages_he.properties
native2ascii -encoding utf8 text_utf8\messages_it_IT.properties text\messages_it_IT.properties
native2ascii -encoding utf8 text_utf8\messages_ja.properties text\messages_ja.properties
native2ascii -encoding utf8 text_utf8\messages_km.properties text\messages_km.properties
native2ascii -encoding utf8 text_utf8\messages_ko.properties text\messages_ko.properties
native2ascii -encoding utf8 text_utf8\messages_ksh.properties text\messages_ksh.properties
native2ascii -encoding utf8 text_utf8\messages_lb.properties text\messages_lb.properties
native2ascii -encoding utf8 text_utf8\messages_lt.properties text\messages_lt.properties
native2ascii -encoding utf8 text_utf8\messages_mk.properties text\messages_mk.properties
native2ascii -encoding utf8 text_utf8\messages_ml.properties text\messages_ml.properties
native2ascii -encoding utf8 text_utf8\messages_mr.properties text\messages_mr.properties
native2ascii -encoding utf8 text_utf8\messages_ms.properties text\messages_ms.properties
native2ascii -encoding utf8 text_utf8\messages_nl.properties text\messages_nl.properties
native2ascii -encoding utf8 text_utf8\messages_oc.properties text\messages_oc.properties
native2ascii -encoding utf8 text_utf8\messages_pa.properties text\messages_pa.properties
native2ascii -encoding utf8 text_utf8\messages_pl_PL.properties text\messages_pl_PL.properties
native2ascii -encoding utf8 text_utf8\messages_pt_BR.properties text\messages_pt_BR.properties
native2ascii -encoding utf8 text_utf8\messages_pt_PT.properties text\messages_pt_PT.properties
native2ascii -encoding utf8 text_utf8\messages_ru.properties text\messages_ru.properties
native2ascii -encoding utf8 text_utf8\messages_sr-ec.properties text\messages_sr-ec.properties
native2ascii -encoding utf8 text_utf8\messages_sv_SE.properties text\messages_sv_SE.properties
native2ascii -encoding utf8 text_utf8\messages_tr.properties text\messages_tr.properties
native2ascii -encoding utf8 text_utf8\messages_tt-cyrl.properties text\messages_tt-cyrl.properties
native2ascii -encoding utf8 text_utf8\messages_uk.properties text\messages_uk.properties
native2ascii -encoding utf8 text_utf8\messages_ur.properties text\messages_ur.properties
native2ascii -encoding utf8 text_utf8\messages_zh-hant.properties text\messages_zh-hant.properties
native2ascii -encoding utf8 text_utf8\messages_zh_CN.properties text\messages_zh_CN.properties